### ISSUE TITLE
Remove HTML editing

### ISSUE THREAD

**Issue by adambricelis** [Code4Community/git-tutorial#68]
To complete the tutorial, new members should only have to add their photo to the images folder.

We need to automate adding images to the page in a way that avoids merge conflicts. We could do something with GitHub actions CI, or we could use Python or JavaScript to scan the images folder and serve the images.

**Comment by ndrewh** [comment]
Hmm, I wonder how much this could be mitigated by having people add themselves in non-overlapping slots. ie. you could just partition the body of the HTML like this ahead of the workshop:

```
<!-- Slot 1 -->

<!-- Slot 2 -->

<!-- Slot 3 -->
...
```
probably go for 100 slots:

```python
for x in range(100):
    print(f'<!-- Slot {x+1} -->\n')
```

Then just have people count-off (elementary school style) to assign themselves numbers, and then I would guess you would avoid merge conflicts, while still letting people merge real code into the repo. Haven't proven this works though.

**Comment by adambricelis** [comment]
Something like [this](https://stackoverflow.com/questions/18480550/how-to-load-all-the-images-from-one-of-my-folder-into-my-web-page-using-jquery/32940532) could work (although we would do it in vanilla JS).

Here's a rough outline of the algorithm I have in mind:
1. Get a list of all of the files in the images folder
1. For each file (really just a file name), insert a `person-frame-inner` DOM node into the `heads-area`

This would simplify the tutorial by removing any HTML editing. New members would only add their pictures to the images folder when they commit to this repository. I personally think editing HTML should be out of scope for this tutorial since we don't cover HTML until the next tutorial.

**Comment by ndrewh** [comment]
I see what you mean, but I think actually editing code is pretty important to properly understand what Git does and how GitHub works.

I think 2221 still does HTML in the first lab, so my guess was it's safe enough to assume they won't be totally lost. (Plus it's basically just copy/paste and change name and URL)
